spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/blogs_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull&allowPublicKeyRetrieval=true
    username: testuser
    password: 5678
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
logging:
  level:
    site.itseasy.blog: debug